"""Added onboard values to the models

Revision ID: 09574c10292e
Revises: 5cf22f4f46ed
Create Date: 2025-01-04 01:13:43.863565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09574c10292e'
down_revision = '5cf22f4f46ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hdd_or_ssd_onboard', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('memory_onboard', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('memory_onboard')
        batch_op.drop_column('hdd_or_ssd_onboard')

    # ### end Alembic commands ###
